### ISSUE TITLE
import with absolute file path not working

### ISSUE THREAD

**Issue by NexZhu** [unjs/jiti#104]
### Environment

Node.js v19.3.0
Typescript 4.8.4
jiti 1.16.0

### Reproduction

Easy to reproduce

### Describe the bug

From `src/app.ts`, `import { xxx } from './auth' ` works as expected by `import { xxx } from src/auth` won't work:
```
Error: Cannot find module 'src/auth'
Require stack:
- /root/dev/xxx/src/app.ts
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at _resolve (/root/dev/xxx/node_modules/.pnpm/jiti@1.16.0/node_modules/jiti/dist/jiti.js:1:243302)
    at jiti (/root/dev/xxx/node_modules/.pnpm/jiti@1.16.0/node_modules/jiti/dist/jiti.js:1:245428)
    at /root/dev/xxx/src/app.ts:20:13
    at jiti (/root/dev/xxx/node_modules/.pnpm/jiti@1.16.0/node_modules/jiti/dist/jiti.js:1:247502)
    at Object.<anonymous> (/root/dev/xxx/node_modules/.pnpm/jiti@1.16.0/node_modules/jiti/bin/jiti.js:16:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/dev/xxx/src/app.ts' ]
}
```

With `ts-node` both work as expected.

**Comment by pi0** [comment]
Hi. You probably are defining aliases in tsconfig. jiti uses isolated environment (not reading them)

**Comment by pi0** [comment]
(please ping to reopen if you feel it is unexpected behavior)

**Comment by dzcpy** [comment]
So is there any config that I can make sure custom path aliases defined in tsconfig.json are picked up?
