### ISSUE TITLE
SyntaxError: Unexpected token in: node_modules/jiti/dist/types.d.ts

### ISSUE THREAD

**Issue by acidjazz** [unjs/jiti#49]
I'm not sure where this belongs - I'm hoping here.  

I'm using unbuild/nuxt-kit for the nuxt module of my package [tailvue](https://github.com/fumeapp/tailvue)

I get this error while trying to build for my nuxt module in `packages/nuxt`

Here is my build config:

```ts
import { defineBuildConfig } from 'unbuild';

export default defineBuildConfig({
  declaration: true,
  entries: [
    'src/module',
    {
      input: 'src/runtime/',
      outDir: 'dist/runtime',
      format: 'esm',
      declaration: true
    }
  ],
  externals: [
    '@nuxt/kit-edge',
    'pathe',
  ],
});
```

More detail on my error:

```Error building /Users/k/packages/tailvue/packages/nuxt: SyntaxError: Unexpected token (1:7) in /Users/k/packages/tailvue/packages/nuxt/node_modules/jiti/dist/types.d.ts
SyntaxError: Unexpected token (1:7) in /Users/k/packages/tailvue/packages/nuxt/node_modules/jiti/dist/types.d.ts
    at Parser.pp$5.raise (file:///Users/k/packages/tailvue/packages/nuxt/node_modules/rollup/dist/es/shared/rollup.js:19416:13)
    at Parser.pp.unexpected (file:///Users/k/packages/tailvue/packages/nuxt/node_modules/rollup/dist/es/shared/rollup.js:16741:8)
    at Parser.pp.expect (file:///Users/k/packages/tailvue/packages/nuxt/node_modules/rollup/dist/es/shared/rollup.js:16735:26)
    at Parser.pp$1.parseExportSpecifiers (file:///Users/k/packages/tailvue/packages/nuxt/node_modules/rollup/dist/es/shared/rollup.js:17750:8)
    at Parser.pp$1.parseExport (file:///Users/k/packages/tailvue/packages/nuxt/node_modules/rollup/dist/es/shared/rollup.js:17671:28)
    at Parser.pp$1.parseStatement (file:///Users/k/packages/tailvue/packages/nuxt/node_modules/rollup/dist/es/shared/rollup.js:16917:72)
    at Parser.pp$1.parseTopLevel (file:///Users/k/packages/tailvue/packages/nuxt/node_modules/rollup/dist/es/shared/rollup.js:16798:21)
    at Parser.parse (file:///Users/k/packages/tailvue/packages/nuxt/node_modules/rollup/dist/es/shared/rollup.js:16579:15)
    at Function.parse (file:///Users/k/packages/tailvue/packages/nuxt/node_modules/rollup/dist/es/shared/rollup.js:16621:35)
    at Graph.contextParse (file:///Users/k/packages/tailvue/packages/nuxt/node_modules/rollup/dist/es/shared/rollup.js:22701:38) {
  pos: 7,
  loc: {
    column: 7,
    file: '/Users/k/packages/tailvue/packages/nuxt/node_modules/jiti/dist/types.d.ts',
    line: 1
  },
  raisedAt: 14,
  frame: '1: export declare type TransformOptions = {\n' +
    '          ^\n' +
    '2:     source: string;\n' +
    '3:     filename?: string;',
  id: '/Users/k/packages/tailvue/packages/nuxt/node_modules/jiti/dist/types.d.ts',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'commonjs',```

**Comment by pi0** [comment]
Hi @acidjazz please raise an issue in module-builder / unbuild if having issue with build stoll.
