### ISSUE TITLE
Cannot access 'xxx' before initialization

### ISSUE THREAD

**Issue by as17744** [unjs/jiti#64]
It feels like jiti do not support TS grammar like this : `export declare class xxx`

DEMO:

```ts
// entry.ts
export namespace smart_player_namespace {
  export declare class FeedService {}
}

export type FeedService = smart_player_namespace.FeedService;
export const FeedService = smart_player_namespace.FeedService;
```

The place use jiti:

```js
const createJITI = require('jiti');

const jiti = createJITI();

const content = jiti('./entry.ts');

console.log(content);
```

Then you can find an error:

```bash
ReferenceError: Cannot access 'FeedService' before initialization
    at /Users/bytedance/Documents/demo/jiti-declare/module.ts:1:358
    at /Users/bytedance/Documents/demo/jiti-declare/module.ts:1:372
    at jiti (/Users/bytedance/Documents/demo/jiti-declare/node_modules/jiti/dist/jiti.js:1:196506)
    at /Users/bytedance/Documents/demo/jiti-declare/entry.ts:1:90
    at jiti (/Users/bytedance/Documents/demo/jiti-declare/node_modules/jiti/dist/jiti.js:1:196506)
    at Object.<anonymous> (/Users/bytedance/Documents/demo/jiti-declare/start.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
```

**Comment by hyrious** [comment]
It looks like a babel bug, simple reproduction:

```js
import { transformSync } from "@babel/core";
import typescript from "@babel/plugin-transform-typescript";

let source = `
// entry.ts
export namespace smart_player_namespace {
  export declare class FeedService {}
}

export type FeedService = smart_player_namespace.FeedService;
export const FeedService = smart_player_namespace.FeedService;
`;

let code = transformSync(source, {
  babelrc: false,
  configFile: false,
  compact: false,
  filename: "",
  cwd: "/",
  plugins: [[typescript, { allowDeclareFields: true }]],
}).code;

console.log(code);
console.log("----".repeat(20));

import fs from "fs";

fs.writeFileSync("d.mjs", code);
import("./d.mjs");
```

Output:

```js
// entry.ts
export let smart_player_namespace;

(function (_smart_player_namespace) {
  _smart_player_namespace.FeedService = FeedService;
})(smart_player_namespace || (smart_player_namespace = {}));

export const FeedService = smart_player_namespace.FeedService;
----------------------------------------------------------------------
file:///Users/hyrious/test/d.mjs:5
  _smart_player_namespace.FeedService = FeedService;
                                        ^

ReferenceError: Cannot access 'FeedService' before initialization
```

As a reference, both [TypeScript](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAOwIYFtgGcxIMbDulJWAfTABskBPYKY5NTHPAbwCg45RJY4ATYbBSh5BSdOjgAxYMF4BlGgDcAlrjjMAvqy2su0eDEpg802Qqgq1AXnyES5KjTqoMWXADpT8pauABuXXB9OGwIBHR4L3NLPBsCIhhSCmpaelcmTxlvC18-IA) and [esbuild](https://hyrious.me/esbuild-repl/?version=0.14.49&mode=transform&input=export+namespace+smart_player_namespace+%7B%0A++export+declare+class+FeedService+%7B%7D%0A%7D%0A%0Aexport+type+FeedService+%3D+smart_player_namespace.FeedService%3B%0Aexport+const+FeedService+%3D+smart_player_namespace.FeedService%3B&options=--loader%3Dts) don't generate this line, work as if there's no such `declare` statement.

**Comment by pi0** [comment]
Seems the bug is not reproducable in latest babel/jiti 👍🏼
